In [5]:
import pandas as pd

In [13]:
import numpy as np
arr = np.arange(100, 110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


## Series

In [11]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [14]:
s = pd.Series(arr, dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [46]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [19]:
s = pd.Series([1, 2, 3, 4, 5, '99'])
print(s)

0     1
1     2
2     3
3     4
4     5
5    99
dtype: object


## indexing

In [21]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)

In [23]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
s[1] #음수 인덱싱은 불가능

'lee'

In [31]:
s = pd.Series(person, index=['a', 'b', 'c', 'd']) #index=list('abcd')
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [32]:
s['a']

'kim'

In [34]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [36]:
s.values #인덱스는 제외하고 numpy 배열로 가지고 옴 (array)

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [38]:
s.ndim #차원

1

In [39]:
s.shape

(4,)

### NaN(Not A Number)

In [41]:
s = pd.Series(person + [np.nan]) #np.nan = None
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


```
#1 응용
50.0
51.0
52.0
53.0
54.0
```

In [44]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


### fancy indexing

```
#2 응용
가 바나나
나 NaN
다 사과
라 포도
마 복숭아
```

In [96]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s)
print(s['가':'다']) #다 까지

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object
가    바나나
나    NaN
다     사과
dtype: object


In [97]:
s[['가', '나']]

가    바나나
나    NaN
dtype: object

In [98]:
s.iloc[[2, 3]]


다    사과
라    포도
dtype: object

In [99]:
s[['다', '라']]

다    사과
라    포도
dtype: object

### bool

In [102]:
s[[True, False, True, False, True]]


가    바나나
다     사과
마    복숭아
dtype: object

In [103]:
a = [True, False, True, False, True]
s[a]

가    바나나
다     사과
마    복숭아
dtype: object

In [57]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [58]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [60]:
s [s < 10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

# 결측치(NaN) 처리

In [87]:
s = pd.Series([2, 5, 2, 1, np.nan, 2, 4, 9, np.nan])
print(s)

0    2.0
1    5.0
2    2.0
3    1.0
4    NaN
5    2.0
6    4.0
7    9.0
8    NaN
dtype: float64


In [88]:
s.isnull() #null인 데이터 위치에 True 출력

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [89]:
s[s.isnull()]

4   NaN
8   NaN
dtype: float64

In [90]:
s.isna()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [91]:
s[s.isna()]

4   NaN
8   NaN
dtype: float64

In [92]:
s[s.notnull()]

0    2.0
1    5.0
2    2.0
3    1.0
5    2.0
6    4.0
7    9.0
dtype: float64

In [104]:
s[1:3]

나    NaN
다     사과
dtype: object

## Data Frame

In [107]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [109]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [112]:
df = pd.DataFrame(arr, columns=['가', '나', '다'])
df

가  나  다
0  0  1  2
1  3  4  5
2  6  7  8

In [114]:
df = pd.DataFrame(arr, index=['a', 'b', 'c'])
df

0  1  2
a  0  1  2
b  3  4  5
c  6  7  8

In [116]:
df = pd.DataFrame(arr, columns=['가', '나', '다'], index=['a', 'b', 'c'])
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [118]:
data = {
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location': ['seoul', 'LA', 'tokyo']
}

df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [120]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [122]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [124]:
df.values

array([['kim', 10, 'seoul'],
       ['lee', 15, 'LA'],
       ['park', 20, 'tokyo']], dtype=object)

In [126]:
df.dtypes #컬럼 기준

name        object
age          int64
location    object
dtype: object

In [128]:
df.T #인덱스와 컬럼 위치 바꾸기

0    1      2
name        kim  lee   park
age          10   15     20
location  seoul   LA  tokyo

In [130]:
df.index = list('abc')
df

name  age location
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo

### column

In [131]:
df['name']

a     kim
b     lee
c    park
Name: name, dtype: object

In [132]:
type(df['name'])

pandas.core.series.Series

In [133]:
df[['name', 'location']]

name location
a   kim    seoul
b   lee       LA
c  park    tokyo

In [134]:
type(df[['name', 'location']])

pandas.core.frame.DataFrame

In [142]:
df.rename(columns={'hometown': 'location'}) #출력만

AttributeError: 'NoneType' object has no attribute 'rename'

In [141]:
df.rename(columns={'location': 'hometown'}, inplace=True)

AttributeError: 'NoneType' object has no attribute 'rename'

In [138]:
df = df.rename(columns={'location': 'hometown'}) #원본 수정
df

AttributeError: 'NoneType' object has no attribute 'rename'